### ISSUE TITLE
debugLifecycleState != _ElementLifecycle.defunct': is not true

### ISSUE THREAD

**Issue by seyhadot** [kiatuki/animated_qr_code_scanner#2]
Hi what should i do because i always get this error
════════ (953) Exception caught by animation library ═══════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 3867 pos 12: '_debugLifecycleState != _ElementLifecycle.defunct': is not true.

**Comment by kiatuki** [comment]
Fixed on #3. Thank you.
